[tool.poetry]
name = "warm64_server"
version = "0.1.0"
description = ""
authors = ["Tim Misiak"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
